// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PLManagementSystem.Data.Entites;

#nullable disable

namespace PLManagementSystem.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240823153542_AddTableClassesUpgradeOrdering")]
    partial class AddTableClassesUpgradeOrdering
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PLManagementSystem.Core.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "First Grade Primary",
                            OrderNo = 1,
                            ShortName = "First Primary"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Second Grade Primary",
                            OrderNo = 2,
                            ShortName = "Second Primary"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Third Grade Primary",
                            OrderNo = 3,
                            ShortName = "Third Primary"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Fourth Grade Primary",
                            OrderNo = 4,
                            ShortName = "Fourth Primary"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Fifth Grade Primary",
                            OrderNo = 5,
                            ShortName = "Fifth Primary"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Name = "Sixth Grade Primary",
                            OrderNo = 6,
                            ShortName = "Sixth Primary"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Name = "First Grade Preparatory",
                            OrderNo = 7,
                            ShortName = "First Prep"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Name = "Second Grade Preparatory",
                            OrderNo = 8,
                            ShortName = "Second Prep"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            Name = "Third Grade Preparatory",
                            OrderNo = 9,
                            ShortName = "Third Prep"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            Name = "First Grade Secondary",
                            OrderNo = 10,
                            ShortName = "First Secondary"
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            Name = "Second Grade Secondary",
                            OrderNo = 11,
                            ShortName = "Second Secondary"
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            Name = "Third Grade Secondary",
                            OrderNo = 12,
                            ShortName = "Third Secondary"
                        });
                });

            modelBuilder.Entity("PLManagementSystem.Core.Entities.ClassesUpgradeOrdering", b =>
                {
                    b.Property<int>("LowerClassId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("UpperClassId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("LowerClassId", "UpperClassId");

                    b.HasIndex("UpperClassId");

                    b.ToTable("ClassesUpgradeOrdering");

                    b.HasData(
                        new
                        {
                            LowerClassId = 1,
                            UpperClassId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            LowerClassId = 2,
                            UpperClassId = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            LowerClassId = 3,
                            UpperClassId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            LowerClassId = 4,
                            UpperClassId = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            LowerClassId = 5,
                            UpperClassId = 6,
                            IsDeleted = false
                        },
                        new
                        {
                            LowerClassId = 6,
                            UpperClassId = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            LowerClassId = 7,
                            UpperClassId = 8,
                            IsDeleted = false
                        },
                        new
                        {
                            LowerClassId = 8,
                            UpperClassId = 9,
                            IsDeleted = false
                        },
                        new
                        {
                            LowerClassId = 9,
                            UpperClassId = 10,
                            IsDeleted = false
                        },
                        new
                        {
                            LowerClassId = 10,
                            UpperClassId = 11,
                            IsDeleted = false
                        },
                        new
                        {
                            LowerClassId = 11,
                            UpperClassId = 12,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("PLManagementSystem.Core.Entities.Day", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Dayes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Saturday"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Sunday"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Monday"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Tuesday"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Wednesday"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Name = "Thursday"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Name = "Friday"
                        });
                });

            modelBuilder.Entity("PLManagementSystem.Core.Entities.LessonGroups", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("LessonGroups");
                });

            modelBuilder.Entity("PLManagementSystem.Core.Entities.LessonGroupsDays", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LessonGroupId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("LessonGroupId");

                    b.ToTable("LessonGroupsDays");
                });

            modelBuilder.Entity("PLManagementSystem.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PLManagementSystem.Core.Entities.ClassesUpgradeOrdering", b =>
                {
                    b.HasOne("PLManagementSystem.Core.Entities.Class", "LowerClass")
                        .WithMany()
                        .HasForeignKey("LowerClassId")
                        .IsRequired();

                    b.HasOne("PLManagementSystem.Core.Entities.Class", "UpperClass")
                        .WithMany()
                        .HasForeignKey("UpperClassId")
                        .IsRequired();

                    b.Navigation("LowerClass");

                    b.Navigation("UpperClass");
                });

            modelBuilder.Entity("PLManagementSystem.Core.Entities.LessonGroups", b =>
                {
                    b.HasOne("PLManagementSystem.Core.Entities.Class", "Classes")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classes");
                });

            modelBuilder.Entity("PLManagementSystem.Core.Entities.LessonGroupsDays", b =>
                {
                    b.HasOne("PLManagementSystem.Core.Entities.Day", "Dayes")
                        .WithMany()
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PLManagementSystem.Core.Entities.LessonGroups", "LessonGroup")
                        .WithMany("LessonGroupsDays")
                        .HasForeignKey("LessonGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dayes");

                    b.Navigation("LessonGroup");
                });

            modelBuilder.Entity("PLManagementSystem.Core.Entities.LessonGroups", b =>
                {
                    b.Navigation("LessonGroupsDays");
                });
#pragma warning restore 612, 618
        }
    }
}
